name: seizure-prediction
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.12
  - mne
  - numpy
  - matplotlib
  - scikit-learn
  - scipy
  - toml
  - tqdm
  - prettytable
  - pytorch
  - torchvision
  - pytorch-gpu
  - tensorboard
